report_sizes: true

gomod:
  proxy: true

  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

  mod: mod

builds:
  - id: "in-addr"
    main: ./cmd/in-addr
    binary: in-addr
    flags:
      - -trimpath
      - -buildvcs=true
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 5
      - 6
      - 7
    goamd64:
      - v2
      - v3

    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: false
    no_unique_dist_dir: false
    no_main_check: true
